include_recipe 'gnustep-dev::dependencies'
include_recipe 'gnustep-dev::devel-user'
include_recipe 'gnustep-dev::download-source'
include_recipe 'gnustep-dev::compile'
#include_recipe 'gnustep-dev::restore-user-permissions'
